
public class Song
{
	public int Id { get; set; } // Autogenerated by database
	public string Title {get; set;}
	public string Artist { get; set; }
	public string Genre { get; set; }
	public string RecordLabel { get; set; }
	public int ReleaseYear { get; set; }
}